import "dotenv/config";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const ports = [
  // ── 중동 ──
  { name: "Jebel Ali", nameKo: "제벨알리", unlocode: "AEJEA", lat: 25.01, lon: 55.05, country: "UAE" },
  { name: "Abu Dhabi", nameKo: "아부다비", unlocode: "AEAUH", lat: 24.47, lon: 54.37, country: "UAE" },
  { name: "Sharjah", nameKo: "샤르자", unlocode: "AESHJ", lat: 25.35, lon: 55.38, country: "UAE" },
  { name: "Fujairah", nameKo: "푸자이라", unlocode: "AEFUJ", lat: 25.12, lon: 56.35, country: "UAE" },
  { name: "Khor Fakkan", nameKo: "코르파칸", unlocode: "AEKHF", lat: 25.34, lon: 56.37, country: "UAE" },
  { name: "Ruwais", nameKo: "루와이스", unlocode: "AERUW", lat: 24.11, lon: 52.73, country: "UAE" },
  { name: "Jubail", nameKo: "주바일", unlocode: "SAJUB", lat: 27.02, lon: 49.62, country: "Saudi Arabia" },
  { name: "Dammam", nameKo: "담맘", unlocode: "SADMM", lat: 26.44, lon: 50.15, country: "Saudi Arabia" },
  { name: "Yanbu", nameKo: "얀부", unlocode: "SAYNB", lat: 24.09, lon: 38.05, country: "Saudi Arabia" },
  { name: "Jeddah", nameKo: "제다", unlocode: "SAJED", lat: 21.49, lon: 39.17, country: "Saudi Arabia" },
  { name: "Ras Tanura", nameKo: "라스타누라", unlocode: "SARTA", lat: 26.65, lon: 50.16, country: "Saudi Arabia" },
  { name: "Jizan", nameKo: "지잔", unlocode: "SAJIZ", lat: 16.90, lon: 42.55, country: "Saudi Arabia" },
  { name: "Rabigh", nameKo: "라비그", unlocode: "SARAB", lat: 22.80, lon: 39.03, country: "Saudi Arabia" },
  { name: "Kuwait (Shuwaikh)", nameKo: "쿠웨이트", unlocode: "KWKWI", lat: 29.35, lon: 47.95, country: "Kuwait" },
  { name: "Shuaiba", nameKo: "슈아이바", unlocode: "KWSHU", lat: 29.05, lon: 48.15, country: "Kuwait" },
  { name: "Khalifa Bin Salman", nameKo: "칼리파빈살만", unlocode: "BHKBS", lat: 26.18, lon: 50.52, country: "Bahrain" },
  { name: "Hamad Port", nameKo: "하마드항", unlocode: "QAHMD", lat: 24.96, lon: 51.56, country: "Qatar" },
  { name: "Ras Laffan", nameKo: "라스라판", unlocode: "QARLF", lat: 25.90, lon: 51.58, country: "Qatar" },
  { name: "Mesaieed", nameKo: "메사이드", unlocode: "QAMES", lat: 24.98, lon: 51.55, country: "Qatar" },
  { name: "Muscat (Muttrah)", nameKo: "무스카트", unlocode: "OMMCT", lat: 23.62, lon: 58.59, country: "Oman" },
  { name: "Sohar", nameKo: "소하르", unlocode: "OMSOH", lat: 24.35, lon: 56.63, country: "Oman" },
  { name: "Salalah", nameKo: "살랄라", unlocode: "OMSLL", lat: 16.94, lon: 54.00, country: "Oman" },
  { name: "Duqm", nameKo: "두쿰", unlocode: "OMDUQ", lat: 19.65, lon: 57.70, country: "Oman" },
  { name: "Bandar Abbas", nameKo: "반다르압바스", unlocode: "IRBND", lat: 27.18, lon: 56.28, country: "Iran" },
  { name: "Bandar Imam Khomeini", nameKo: "반다르이맘호메이니", unlocode: "IRIMK", lat: 30.43, lon: 49.08, country: "Iran" },
  { name: "Bushehr", nameKo: "부셰르", unlocode: "IRBUZ", lat: 28.98, lon: 50.84, country: "Iran" },
  { name: "Chabahar", nameKo: "차바하르", unlocode: "IRZBR", lat: 25.29, lon: 60.64, country: "Iran" },
  { name: "Umm Qasr", nameKo: "움카스르", unlocode: "IQUQR", lat: 30.03, lon: 47.93, country: "Iraq" },
  { name: "Basra", nameKo: "바스라", unlocode: "IQBSR", lat: 30.52, lon: 47.82, country: "Iraq" },
  { name: "Haifa", nameKo: "하이파", unlocode: "ILHFA", lat: 32.82, lon: 35.00, country: "Israel" },
  { name: "Ashdod", nameKo: "아쉬도드", unlocode: "ILASH", lat: 31.82, lon: 34.65, country: "Israel" },
  { name: "Aqaba", nameKo: "아카바", unlocode: "JOAQJ", lat: 29.52, lon: 35.00, country: "Jordan" },
  { name: "Port Said", nameKo: "포트사이드", unlocode: "EGPSD", lat: 31.25, lon: 32.30, country: "Egypt" },
  { name: "Suez", nameKo: "수에즈", unlocode: "EGSUZ", lat: 29.97, lon: 32.55, country: "Egypt" },
  { name: "Alexandria", nameKo: "알렉산드리아", unlocode: "EGALY", lat: 31.20, lon: 29.90, country: "Egypt" },
  { name: "Damietta", nameKo: "다미에타", unlocode: "EGDAM", lat: 31.45, lon: 31.80, country: "Egypt" },
  { name: "Ain Sukhna", nameKo: "아인수크나", unlocode: "EGASK", lat: 29.60, lon: 32.35, country: "Egypt" },
  { name: "Aden", nameKo: "아덴", unlocode: "YEADE", lat: 12.78, lon: 44.99, country: "Yemen" },
  { name: "Istanbul (Haydarpasa)", nameKo: "이스탄불", unlocode: "TRISK", lat: 41.00, lon: 29.02, country: "Turkey" },
  { name: "Ambarli", nameKo: "암바를르", unlocode: "TRAME", lat: 41.01, lon: 28.69, country: "Turkey" },
  { name: "Izmir", nameKo: "이즈미르", unlocode: "TRIZM", lat: 38.43, lon: 27.14, country: "Turkey" },
  { name: "Mersin", nameKo: "메르신", unlocode: "TRMER", lat: 36.80, lon: 34.63, country: "Turkey" },
  { name: "Iskenderun", nameKo: "이스켄데룬", unlocode: "TRISK", lat: 36.58, lon: 36.17, country: "Turkey" },

  // ── 아프리카 (동아프리카·홍해) ──
  { name: "Djibouti", nameKo: "지부티", unlocode: "DJJIB", lat: 11.60, lon: 43.15, country: "Djibouti" },
  { name: "Berbera", nameKo: "베르베라", unlocode: "SOBER", lat: 10.44, lon: 45.01, country: "Somalia" },
  { name: "Mombasa", nameKo: "몸바사", unlocode: "KEMBA", lat: -4.05, lon: 39.66, country: "Kenya" },
  { name: "Dar es Salaam", nameKo: "다르에스살람", unlocode: "TZDAR", lat: -6.82, lon: 39.29, country: "Tanzania" },
  { name: "Beira", nameKo: "베이라", unlocode: "MZBEW", lat: -19.84, lon: 34.84, country: "Mozambique" },
  { name: "Maputo", nameKo: "마푸투", unlocode: "MZMPM", lat: -25.97, lon: 32.60, country: "Mozambique" },
  { name: "Durban", nameKo: "더반", unlocode: "ZADUR", lat: -29.87, lon: 31.05, country: "South Africa" },
  { name: "Port Elizabeth", nameKo: "포트엘리자베스", unlocode: "ZAPLZ", lat: -33.96, lon: 25.63, country: "South Africa" },
  { name: "Cape Town", nameKo: "케이프타운", unlocode: "ZACPT", lat: -33.91, lon: 18.43, country: "South Africa" },
  { name: "Lagos (Apapa)", nameKo: "라고스", unlocode: "NGLOS", lat: 6.45, lon: 3.39, country: "Nigeria" },
  { name: "Abidjan", nameKo: "아비장", unlocode: "CIABJ", lat: 5.34, lon: -4.01, country: "Ivory Coast" },
  { name: "Tema", nameKo: "테마", unlocode: "GHTEM", lat: 5.64, lon: -0.01, country: "Ghana" },
  { name: "Dakar", nameKo: "다카르", unlocode: "SNDKR", lat: 14.69, lon: -17.44, country: "Senegal" },
  { name: "Casablanca", nameKo: "카사블랑카", unlocode: "MACAS", lat: 33.60, lon: -7.62, country: "Morocco" },
  { name: "Tangier Med", nameKo: "탕헤르메드", unlocode: "MATNG", lat: 35.88, lon: -5.50, country: "Morocco" },

  // ── 남아시아 ──
  { name: "Mumbai (JNPT)", nameKo: "뭄바이 JNPT", unlocode: "INNSA", lat: 18.95, lon: 72.95, country: "India" },
  { name: "Mumbai (Nhava Sheva)", nameKo: "뭄바이항", unlocode: "INBOM", lat: 18.94, lon: 72.84, country: "India" },
  { name: "Chennai", nameKo: "첸나이", unlocode: "INMAA", lat: 13.09, lon: 80.30, country: "India" },
  { name: "Kolkata", nameKo: "콜카타", unlocode: "INCCU", lat: 22.57, lon: 88.31, country: "India" },
  { name: "Haldia", nameKo: "할디아", unlocode: "INHLD", lat: 22.04, lon: 88.10, country: "India" },
  { name: "Visakhapatnam", nameKo: "비사카파트남", unlocode: "INVTZ", lat: 17.69, lon: 83.28, country: "India" },
  { name: "Mundra", nameKo: "문드라", unlocode: "INMUN", lat: 22.84, lon: 69.72, country: "India" },
  { name: "Kandla", nameKo: "칸들라", unlocode: "INKLA", lat: 23.02, lon: 70.22, country: "India" },
  { name: "Cochin (Kochi)", nameKo: "코치", unlocode: "INCOK", lat: 9.97, lon: 76.27, country: "India" },
  { name: "Tuticorin", nameKo: "투티코린", unlocode: "INTUT", lat: 8.76, lon: 78.14, country: "India" },
  { name: "Hazira", nameKo: "하지라", unlocode: "INHAZ", lat: 21.09, lon: 72.62, country: "India" },
  { name: "Mormugao", nameKo: "모르무가오", unlocode: "INMRM", lat: 15.41, lon: 73.80, country: "India" },
  { name: "Ennore (Kamarajar)", nameKo: "엔노르", unlocode: "INENN", lat: 13.21, lon: 80.33, country: "India" },
  { name: "Colombo", nameKo: "콜롬보", unlocode: "LKCMB", lat: 6.93, lon: 79.84, country: "Sri Lanka" },
  { name: "Hambantota", nameKo: "함반토타", unlocode: "LKHBA", lat: 6.12, lon: 81.12, country: "Sri Lanka" },
  { name: "Karachi", nameKo: "카라치", unlocode: "PKKHI", lat: 24.86, lon: 67.00, country: "Pakistan" },
  { name: "Port Qasim", nameKo: "포트카심", unlocode: "PKPQQ", lat: 24.78, lon: 67.32, country: "Pakistan" },
  { name: "Gwadar", nameKo: "과다르", unlocode: "PKGWD", lat: 25.12, lon: 62.33, country: "Pakistan" },
  { name: "Chittagong", nameKo: "치타공", unlocode: "BDCGP", lat: 22.33, lon: 91.82, country: "Bangladesh" },
  { name: "Mongla", nameKo: "몽글라", unlocode: "BDMGL", lat: 22.48, lon: 89.59, country: "Bangladesh" },
  { name: "Yangon", nameKo: "양곤", unlocode: "MMRGN", lat: 16.78, lon: 96.18, country: "Myanmar" },

  // ── 동남아시아 ──
  { name: "Singapore", nameKo: "싱가포르", unlocode: "SGSIN", lat: 1.26, lon: 103.82, country: "Singapore" },
  { name: "Port Klang", nameKo: "포트클랑", unlocode: "MYPKG", lat: 3.00, lon: 101.38, country: "Malaysia" },
  { name: "Tanjung Pelepas", nameKo: "탄중펠레파스", unlocode: "MYTWU", lat: 1.36, lon: 103.55, country: "Malaysia" },
  { name: "Penang", nameKo: "페낭", unlocode: "MYPGU", lat: 5.41, lon: 100.38, country: "Malaysia" },
  { name: "Bintulu", nameKo: "빈툴루", unlocode: "MYBTU", lat: 3.17, lon: 113.04, country: "Malaysia" },
  { name: "Laem Chabang", nameKo: "렘차방", unlocode: "THLCH", lat: 13.08, lon: 100.88, country: "Thailand" },
  { name: "Bangkok", nameKo: "방콕", unlocode: "THBKK", lat: 13.73, lon: 100.50, country: "Thailand" },
  { name: "Map Ta Phut", nameKo: "맵타풋", unlocode: "THMTP", lat: 12.68, lon: 101.15, country: "Thailand" },
  { name: "Tanjung Priok (Jakarta)", nameKo: "탄중프리옥", unlocode: "IDJKT", lat: -6.10, lon: 106.88, country: "Indonesia" },
  { name: "Surabaya (Tanjung Perak)", nameKo: "수라바야", unlocode: "IDSUB", lat: -7.20, lon: 112.74, country: "Indonesia" },
  { name: "Belawan (Medan)", nameKo: "벨라완", unlocode: "IDBEL", lat: 3.79, lon: 98.70, country: "Indonesia" },
  { name: "Makassar", nameKo: "마카사르", unlocode: "IDMAK", lat: -5.12, lon: 119.41, country: "Indonesia" },
  { name: "Balikpapan", nameKo: "발릭파판", unlocode: "IDBPN", lat: -1.27, lon: 116.83, country: "Indonesia" },
  { name: "Ho Chi Minh City", nameKo: "호치민", unlocode: "VNSGN", lat: 10.71, lon: 106.73, country: "Vietnam" },
  { name: "Cai Mep", nameKo: "카이맵", unlocode: "VNCME", lat: 10.56, lon: 107.02, country: "Vietnam" },
  { name: "Haiphong", nameKo: "하이퐁", unlocode: "VNHPH", lat: 20.86, lon: 106.69, country: "Vietnam" },
  { name: "Da Nang", nameKo: "다낭", unlocode: "VNDAD", lat: 16.09, lon: 108.22, country: "Vietnam" },
  { name: "Manila", nameKo: "마닐라", unlocode: "PHMNL", lat: 14.57, lon: 120.97, country: "Philippines" },
  { name: "Cebu", nameKo: "세부", unlocode: "PHCEB", lat: 10.28, lon: 123.90, country: "Philippines" },
  { name: "Davao", nameKo: "다바오", unlocode: "PHDVO", lat: 7.08, lon: 125.61, country: "Philippines" },
  { name: "Sihanoukville", nameKo: "시하누크빌", unlocode: "KHKOS", lat: 10.63, lon: 103.52, country: "Cambodia" },
  { name: "Muara", nameKo: "무아라", unlocode: "BNMUA", lat: 5.02, lon: 115.06, country: "Brunei" },

  // ── 동북아시아 ──
  { name: "Shanghai", nameKo: "상하이", unlocode: "CNSHA", lat: 31.23, lon: 121.47, country: "China" },
  { name: "Ningbo-Zhoushan", nameKo: "닝보저우산", unlocode: "CNNGB", lat: 29.89, lon: 122.10, country: "China" },
  { name: "Shenzhen (Yantian)", nameKo: "옌톈", unlocode: "CNSZN", lat: 22.57, lon: 114.26, country: "China" },
  { name: "Shenzhen (Shekou)", nameKo: "서커우", unlocode: "CNSKN", lat: 22.48, lon: 113.91, country: "China" },
  { name: "Guangzhou (Nansha)", nameKo: "광저우 난사", unlocode: "CNGZU", lat: 22.73, lon: 113.55, country: "China" },
  { name: "Tianjin", nameKo: "텐진", unlocode: "CNTSN", lat: 38.99, lon: 117.74, country: "China" },
  { name: "Qingdao", nameKo: "칭다오", unlocode: "CNTAO", lat: 36.07, lon: 120.37, country: "China" },
  { name: "Dalian", nameKo: "다롄", unlocode: "CNDLC", lat: 38.92, lon: 121.63, country: "China" },
  { name: "Xiamen", nameKo: "샤먼", unlocode: "CNXMN", lat: 24.48, lon: 118.08, country: "China" },
  { name: "Lianyungang", nameKo: "롄윈강", unlocode: "CNLYG", lat: 34.73, lon: 119.44, country: "China" },
  { name: "Yantai", nameKo: "옌타이", unlocode: "CNYNT", lat: 37.54, lon: 121.39, country: "China" },
  { name: "Fuzhou", nameKo: "푸저우", unlocode: "CNFOC", lat: 25.98, lon: 119.37, country: "China" },
  { name: "Nanjing", nameKo: "난징", unlocode: "CNNKG", lat: 31.96, lon: 118.79, country: "China" },
  { name: "Zhuhai", nameKo: "주하이", unlocode: "CNZUH", lat: 22.27, lon: 113.60, country: "China" },
  { name: "Hong Kong", nameKo: "홍콩", unlocode: "HKHKG", lat: 22.29, lon: 114.16, country: "Hong Kong" },
  { name: "Busan", nameKo: "부산", unlocode: "KRBSN", lat: 35.10, lon: 129.04, country: "South Korea" },
  { name: "Incheon", nameKo: "인천", unlocode: "KRICN", lat: 37.46, lon: 126.61, country: "South Korea" },
  { name: "Gwangyang", nameKo: "광양", unlocode: "KRKWJ", lat: 34.90, lon: 127.70, country: "South Korea" },
  { name: "Ulsan", nameKo: "울산", unlocode: "KRULS", lat: 35.53, lon: 129.38, country: "South Korea" },
  { name: "Pohang", nameKo: "포항", unlocode: "KRPOH", lat: 36.03, lon: 129.38, country: "South Korea" },
  { name: "Pyeongtaek", nameKo: "평택", unlocode: "KRPTK", lat: 36.99, lon: 126.83, country: "South Korea" },
  { name: "Yeosu", nameKo: "여수", unlocode: "KRYOS", lat: 34.74, lon: 127.74, country: "South Korea" },
  { name: "Tokyo", nameKo: "도쿄", unlocode: "JPTYO", lat: 35.65, lon: 139.77, country: "Japan" },
  { name: "Yokohama", nameKo: "요코하마", unlocode: "JPYOK", lat: 35.45, lon: 139.65, country: "Japan" },
  { name: "Nagoya", nameKo: "나고야", unlocode: "JPNGO", lat: 35.07, lon: 136.88, country: "Japan" },
  { name: "Osaka", nameKo: "오사카", unlocode: "JPOSA", lat: 34.65, lon: 135.43, country: "Japan" },
  { name: "Kobe", nameKo: "고베", unlocode: "JPUKB", lat: 34.68, lon: 135.19, country: "Japan" },
  { name: "Hakata (Fukuoka)", nameKo: "하카타", unlocode: "JPFUK", lat: 33.60, lon: 130.41, country: "Japan" },
  { name: "Kitakyushu", nameKo: "기타큐슈", unlocode: "JPKIJ", lat: 33.87, lon: 130.84, country: "Japan" },
  { name: "Kaohsiung", nameKo: "가오슝", unlocode: "TWKHH", lat: 22.62, lon: 120.27, country: "Taiwan" },
  { name: "Taichung", nameKo: "타이중", unlocode: "TWTXG", lat: 24.28, lon: 120.52, country: "Taiwan" },
  { name: "Keelung", nameKo: "지룽", unlocode: "TWKEL", lat: 25.13, lon: 121.74, country: "Taiwan" },

  // ── 유럽 ──
  { name: "Rotterdam", nameKo: "로테르담", unlocode: "NLRTM", lat: 51.95, lon: 4.14, country: "Netherlands" },
  { name: "Amsterdam", nameKo: "암스테르담", unlocode: "NLAMS", lat: 52.37, lon: 4.91, country: "Netherlands" },
  { name: "Hamburg", nameKo: "함부르크", unlocode: "DEHAM", lat: 53.55, lon: 9.97, country: "Germany" },
  { name: "Bremerhaven", nameKo: "브레머하펜", unlocode: "DEBRV", lat: 53.54, lon: 8.58, country: "Germany" },
  { name: "Antwerp", nameKo: "앤트워프", unlocode: "BEANR", lat: 51.26, lon: 4.40, country: "Belgium" },
  { name: "Zeebrugge", nameKo: "제브뤼헤", unlocode: "BEZEE", lat: 51.33, lon: 3.20, country: "Belgium" },
  { name: "Felixstowe", nameKo: "펠릭스토", unlocode: "GBFXT", lat: 51.96, lon: 1.35, country: "UK" },
  { name: "Southampton", nameKo: "사우샘프턴", unlocode: "GBSOU", lat: 50.90, lon: -1.40, country: "UK" },
  { name: "Liverpool", nameKo: "리버풀", unlocode: "GBLIV", lat: 53.40, lon: -3.00, country: "UK" },
  { name: "Immingham", nameKo: "이밍엄", unlocode: "GBIMM", lat: 53.63, lon: -0.19, country: "UK" },
  { name: "Le Havre", nameKo: "르아브르", unlocode: "FRLEH", lat: 49.49, lon: 0.11, country: "France" },
  { name: "Marseille-Fos", nameKo: "마르세유", unlocode: "FRMRS", lat: 43.30, lon: 5.04, country: "France" },
  { name: "Barcelona", nameKo: "바르셀로나", unlocode: "ESBCN", lat: 41.35, lon: 2.17, country: "Spain" },
  { name: "Valencia", nameKo: "발렌시아", unlocode: "ESVLC", lat: 39.45, lon: 0.31, country: "Spain" },
  { name: "Algeciras", nameKo: "알헤시라스", unlocode: "ESALG", lat: 36.13, lon: -5.44, country: "Spain" },
  { name: "Bilbao", nameKo: "빌바오", unlocode: "ESBIO", lat: 43.35, lon: -3.04, country: "Spain" },
  { name: "Genoa", nameKo: "제노바", unlocode: "ITGOA", lat: 44.41, lon: 8.93, country: "Italy" },
  { name: "La Spezia", nameKo: "라스페치아", unlocode: "ITSPZ", lat: 44.11, lon: 9.83, country: "Italy" },
  { name: "Gioia Tauro", nameKo: "조이아타우로", unlocode: "ITGIT", lat: 38.43, lon: 15.90, country: "Italy" },
  { name: "Trieste", nameKo: "트리에스테", unlocode: "ITTRN", lat: 45.65, lon: 13.77, country: "Italy" },
  { name: "Livorno", nameKo: "리보르노", unlocode: "ITLIO", lat: 43.55, lon: 10.31, country: "Italy" },
  { name: "Piraeus", nameKo: "피레우스", unlocode: "GRPIR", lat: 37.95, lon: 23.64, country: "Greece" },
  { name: "Thessaloniki", nameKo: "테살로니키", unlocode: "GRSKU", lat: 40.63, lon: 22.94, country: "Greece" },
  { name: "Marsaxlokk (Malta)", nameKo: "마르사슐로크", unlocode: "MTMAR", lat: 35.84, lon: 14.55, country: "Malta" },
  { name: "Lisbon", nameKo: "리스본", unlocode: "PTLIS", lat: 38.71, lon: -9.15, country: "Portugal" },
  { name: "Sines", nameKo: "시네스", unlocode: "PTSIN", lat: 37.95, lon: -8.87, country: "Portugal" },
  { name: "Gothenburg", nameKo: "예테보리", unlocode: "SEGOT", lat: 57.70, lon: 11.97, country: "Sweden" },
  { name: "Gdansk", nameKo: "그단스크", unlocode: "PLGDN", lat: 54.38, lon: 18.65, country: "Poland" },
  { name: "Limassol", nameKo: "리마솔", unlocode: "CYLMS", lat: 34.67, lon: 33.05, country: "Cyprus" },
  { name: "Constanta", nameKo: "콘스탄차", unlocode: "ROCND", lat: 44.17, lon: 28.66, country: "Romania" },
  { name: "Novorossiysk", nameKo: "노보로시스크", unlocode: "RUNVS", lat: 44.73, lon: 37.78, country: "Russia" },
  { name: "St. Petersburg", nameKo: "상트페테르부르크", unlocode: "RULED", lat: 59.92, lon: 30.24, country: "Russia" },
  { name: "Vladivostok", nameKo: "블라디보스토크", unlocode: "RUVVO", lat: 43.11, lon: 131.90, country: "Russia" },

  // ── 아메리카 ──
  { name: "Los Angeles", nameKo: "로스앤젤레스", unlocode: "USLAX", lat: 33.74, lon: -118.27, country: "USA" },
  { name: "Long Beach", nameKo: "롱비치", unlocode: "USLGB", lat: 33.76, lon: -118.22, country: "USA" },
  { name: "New York / New Jersey", nameKo: "뉴욕", unlocode: "USNYC", lat: 40.67, lon: -74.08, country: "USA" },
  { name: "Houston", nameKo: "휴스턴", unlocode: "USHOU", lat: 29.73, lon: -95.27, country: "USA" },
  { name: "Savannah", nameKo: "사바나", unlocode: "USSAV", lat: 32.08, lon: -81.09, country: "USA" },
  { name: "Seattle / Tacoma", nameKo: "시애틀", unlocode: "USSEA", lat: 47.27, lon: -122.41, country: "USA" },
  { name: "Charleston", nameKo: "찰스턴", unlocode: "USCHS", lat: 32.78, lon: -79.95, country: "USA" },
  { name: "Vancouver", nameKo: "밴쿠버", unlocode: "CAVAN", lat: 49.28, lon: -123.10, country: "Canada" },
  { name: "Santos", nameKo: "산토스", unlocode: "BRSSZ", lat: -23.95, lon: -46.31, country: "Brazil" },
  { name: "Rio de Janeiro", nameKo: "리우데자네이루", unlocode: "BRRIO", lat: -22.90, lon: -43.18, country: "Brazil" },
  { name: "Colon", nameKo: "콜론", unlocode: "PAONX", lat: 9.35, lon: -79.90, country: "Panama" },
  { name: "Cartagena", nameKo: "카르타헤나", unlocode: "COCTG", lat: 10.39, lon: -75.52, country: "Colombia" },
  { name: "Manzanillo (Mexico)", nameKo: "만사니요", unlocode: "MXZLO", lat: 19.05, lon: -104.32, country: "Mexico" },

  // ── 오세아니아 ──
  { name: "Sydney", nameKo: "시드니", unlocode: "AUSYD", lat: -33.86, lon: 151.21, country: "Australia" },
  { name: "Melbourne", nameKo: "멜버른", unlocode: "AUMEL", lat: -37.82, lon: 144.92, country: "Australia" },
  { name: "Brisbane", nameKo: "브리즈번", unlocode: "AUBNE", lat: -27.47, lon: 153.03, country: "Australia" },
  { name: "Fremantle", nameKo: "프리맨틀", unlocode: "AUFRE", lat: -32.05, lon: 115.75, country: "Australia" },
  { name: "Port Hedland", nameKo: "포트헤들랜드", unlocode: "AUPHE", lat: -20.31, lon: 118.57, country: "Australia" },
  { name: "Auckland", nameKo: "오클랜드", unlocode: "NZAKL", lat: -36.84, lon: 174.77, country: "New Zealand" },
];

async function main() {
  console.log(`Seeding ${ports.length} ports...`);
  let inserted = 0, skipped = 0;
  for (const port of ports) {
    try {
      await prisma.port.create({ data: port });
      inserted++;
    } catch (e) {
      if (e.code === "P2002") { skipped++; } // unique constraint (unlocode)
      else console.error(`Error inserting ${port.name}:`, e.message);
    }
  }
  console.log(`Done: ${inserted} inserted, ${skipped} skipped (duplicate)`);
}

main().finally(() => prisma.$disconnect());
